# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
# Profissional Projects ------------------------------


# --------------------------------------------------------------------------------------------------------------


[[main]]
  name = "Portifolio"
  pageRef = "projects"
  weight = 10


[[main]]
  name = "PRJ Category A"
  parent = "Portifolio"
  pageRef = "prj-category-a"
  weight = 10


# BLOG --------------------------------------------------------------------------------------------------------
# SeÃ§Ãµes, â†— Sketchblog, â†— Kaleioscope, â†— Digital Garden

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "10ðŸ“¦ Drops"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/drops/"
  weight = 20

[[main]]
  name = "20ðŸ“° Articles"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/articles/"
  weight = 20

[[main]]
  name = "30ðŸ“„ Notes & Notas"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/notes-notas/"
  weight = 20

[[main]]
  name = "40ðŸ’Š Ins-Pill"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/inspill/"
  weight = 20

[[main]]
  name = "50ðŸ’­ Thoughts"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/thoughts/"
  weight = 20
  
[[main]]
  name = "60ðŸš§ .Log"
  parent = "Blog"
  url = "https://rr-portifolio-blog.pages.dev/pt-br/blog/log/"
  weight = 20

[[main]]
  name = "70ðŸŒŒ See All"
  parent = "Blog"
  pageRef = ""
  weight = 20


# Personal Projects ------------------------------------------------------------------------------------------
# Talvez somente um 

[[main]]
  name = "Personal Projects"
  pageRef = "personal-projects"
  weight = 30


[[main]]
  name = "Design"
  parent = "Personal Projects"
  pageRef = "design"
  weight = 30



# NOW -------------------------------------------------------------------------------------------------------

[[main]]
  name = "Now"
  pageRef = "unique-pages/now"
  weight = 40



# ABOUT ------------------------------------------------------------------------------------------------------

[[main]]
  name = "About"
  pageRef = "unique-pages/about"
  weight = 50


# FOOTER -----------------------------------------------------------------------------------------------------

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 100


[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 100
